### ISSUE TITLE
MONITORING GeoServer ISSUE Bug: Piazza Workspace in GeoServer not properly Initialized in Code

### ISSUE THREAD

**Issue by ssaniev** [venicegeo/bf-api#139]
Pz-Access project, upon startup, creates the Piazza workspace in GeoServer. It first checks to see if the workspace exists, and if it doesn't, it creates it.&nbsp; Beachfront API `bf-api`, at a later point, when initializing, will use this Piazza workspace in order to add its `bfdetections` layer.&nbsp;
There is a problem during initialization of the Piazza workspace. When beachfront runs and registers the `bfdetections` layer, it will register just fine. However, when a user attempts to access the WMS for the bfdetections layer, errors are generated about a missing `piazza:beachfront` schema. These errors are attributed to the Workspace not being properly enabled.&nbsp; This problem can be resolved by, through the web UI, going to the `piazza` workspace page and simply clicking `Save`. This act of clicking Submit/Save on the Workspace, even though no data is changing, is somehow fixing the configuration issue with GeoServer.&nbsp; I (Patrick) am nearly certain that this is a GeoServer bug. However, I don't think we'll see any traction in getting a fix for it. So we probably want some workaround.&nbsp;
To reproduce:
* Fresh GeoServer Instance without any Workspaces/Layers
* Run pz-access to provision the workspace
* Run bf-api to provision the bfdetections layer
* Attempt to access WMS for bfdetections layer
* Error is encountered
At this point, the problem can be fixed by doing a simply onetime action of navigating to the Piazza workspace in the GeoServer Web Admin, and clicking "Save/Submit" .&nbsp; Pz-access attempted to reproduce this behavior by doing another PUT after the workspace creation, but that appears to not have worked.
&nbsp;

**Comment by jphillipsRB** [comment]
Story deleted from ScrumDo
