### ISSUE TITLE
TBD: Add OSM Compute Mask Functionality to Beachfront UI

### ISSUE THREAD

**Issue by ssaniev** [venicegeo/bf-api#209]
As a Beachfront user, I need the user-interface to show me the appropriate input controls for the new parameters related to compute masking with the OSM shoreline dataset.&nbsp;
BF-UI will need a new drop-down parameter that appears when the user checks the existing "apply compute mask" checkbox. This drop-down parameter should show the range of distances that can be buffered on the OSM shoreline dataset. (For a list of these values, probably talk to Mark Dion and figure out what makes the most sense).&nbsp;
The value of this dropdown will have to be sent in the job payload information to bf-api for processing.&nbsp;

**Comment by jphillipsRB** [comment]
Story deleted from ScrumDo
