### ISSUE TITLE
TBD: Update BF-API to support OSM Compute Mask Functionality

### ISSUE THREAD

**Issue by ssaniev** [venicegeo/bf-api#210]
As a BF algorithm writer, I need the API to support the new OSM Compute Mask functionality so that my algorithms can utilize the OSM Compute Masking GeoServer dataset, and are able to receive and transmit the appropriate user-input parameters so that I can read these parameters and apply them to my algorithm.&nbsp;
BF-API will need to update its models to incorporate this new job parameter and ensure this value is passed along to the underlying algorithms through the CLI.&nbsp;
Additionally, since Jobs that define a different buffer-space for a compute mask will have different results, then we technically need to incorporate this parameter into a "redundant job" check. That is to say -- when BF-API determines if a job has been run before, we would previously look to see if that algorithm had been applied to that dataset. Now we need to also check if that identical compute mask setting (with buffer distance) is identical.&nbsp;
This impacts the tables as well. Since we update the Job model, then we'll have to create a liquibase migration to add this new field to the Job parameters table (or perhaps, use the Json Extras)&nbsp;

**Comment by jphillipsRB** [comment]
Story deleted from ScrumDo
