### ISSUE TITLE
TBD: Create new OSM Compute Mask Dataset Management Application

### ISSUE THREAD

**Issue by ssaniev** [venicegeo/bf-api#211]
As a BF algorithm developer, I need a mechanism to query Geoserver for up-to-date OSM Coastline data - so that my algorithm can use proper Coastal Masking from an authoritative dataset in order to produce clean shorelines from my algorithm runs that are free from erroneous artifacts.
Create a PCF application that handles the creation and updates of an authoritative dataset, hosted in GeoServer, that stores up-to-date coastline information that can be used for generating Coastal Masks by algorithms.
This application (something like `bf-osm-coast`) will be responsible from pulling OSM data, tailoring it to our coastline application (perhaps cutting out any unneeded vectors, doing some preprocessing of the data) and pushing that as a dataset to GeoServer. This application will also be responsible for maintaining this dataset on a periodic basis so that the algorithms always have an up-to-date shoreline dataset that can be used to create buffered coastline masks.&nbsp;
This application should attempt to keep the dataset updated every 30 days. If 30 days have passed since the GeoServer dataset has updated, then the dataset should be repopulated from OSM data.&nbsp;BF Developers should be able to manually invoke this process through a public REST endpoint exposed by this application. Additionally, we should create a Jenkins Job (likely in the Tools folder) that allows us to run a Jenkins job to invoke this updating process.
This application, as a PCF app, needs a JenkinsFile pipeline as well that automatically pushes through our three environments (int-&gt;test-&gt;prod) like all other apps to.&nbsp;

**Comment by jphillipsRB** [comment]
Story deleted from ScrumDo
