### ISSUE TITLE
TBD: Update BFAlg-NDWI with new OSM Compute Mask Dataset/Parameters

### ISSUE THREAD

**Issue by ssaniev** [venicegeo/bf-api#212]
As an algorithm developer, I need to pull in the compute mask dataset from GeoServer so that my shorelines can be masked using an up-to-date and authoritative data source.&nbsp;
The current buffering uses a static shapefile dataset of coastlines - which is hard to keep up-to-date and won't scale. By using this new OSM shoreline dataset, curated in GeoServer, the algorithms can apply a coastal mask that is flexible and able to be buffered (since it is a line featureset, not polygons).&nbsp;
Update the algorithm code so that it reads the compute mask parameter, and applies the new "buffer distance" parameter in order to buffer the coastlines that are pulled from the GeoServer OSM shoreline dataset.
&nbsp;

**Comment by jphillipsRB** [comment]
Story deleted from ScrumDo
